name: development

on:
  push:
    branches:
      - development

jobs:
  checkout:
    runs-on:
      labels:
        - self-hosted
        - backend
    steps:
      - name: checkout
        uses: actions/checkout@v4
  build:
    needs: checkout
    runs-on:
      labels:
        - self-hosted
        - backend
    steps:
      - name: build
        run: docker build ./ -f dockerfile -t backend:development
  restart:
    needs: build
    runs-on:
      labels:
        - self-hosted
        - backend
    steps:
      - name: restart
        run: docker compose -p development -f /var/lib/docker/volumes/portainer/_data/compose/1/docker-compose.yml --env-file /var/lib/docker/volumes/portainer/_data/compose/1/stack.env up -d --build